/**
 * main.c — Maze Robot motor test
 *
 * Uses HAL only for clock init (CubeMX-generated SystemClock_Config).
 * All peripheral control is register-level.
 */

/* Includes from CubeMX-generated project */
#include "main.h"
#include "motor.h"

/* ── SysTick millisecond counter ───────────────────────── */
static volatile uint32_t tick_ms = 0;

/*
 * Override the weak SysTick_Handler from HAL.
 * HAL_Init() configures SysTick to fire every 1ms at 168 MHz.
 * We increment both our counter and HAL's uwTick.
 */
void SysTick_Handler(void)
{
    tick_ms++;
    HAL_IncTick();    /* Keep HAL_Delay() working too */
}

static void delay_ms(uint32_t ms)
{
    uint32_t start = tick_ms;
    while ((tick_ms - start) < ms);
}

/* ── Movement primitives (tune on real robot) ──────────── */
#define DEFAULT_SPEED       60
#define TURN_SPEED          50
#define CELL_DRIVE_MS       800
#define TURN_90_MS          450

void move_forward_one_cell(void)
{
    Motor_DriveBoth(DEFAULT_SPEED, DEFAULT_SPEED);
    delay_ms(CELL_DRIVE_MS);
    Motor_Stop();
    delay_ms(100);
}

void turn_left_90(void)
{
    Motor_Drive(MOTOR_LEFT,  MOTOR_BACKWARD, TURN_SPEED);
    Motor_Drive(MOTOR_RIGHT, MOTOR_FORWARD,  TURN_SPEED);
    delay_ms(TURN_90_MS);
    Motor_Stop();
    delay_ms(100);
}

void turn_right_90(void)
{
    Motor_Drive(MOTOR_LEFT,  MOTOR_FORWARD,  TURN_SPEED);
    Motor_Drive(MOTOR_RIGHT, MOTOR_BACKWARD, TURN_SPEED);
    delay_ms(TURN_90_MS);
    Motor_Stop();
    delay_ms(100);
}

void turn_180(void)
{
    turn_left_90();
    turn_left_90();
}

/* ── Debug LEDs (PD12-PD15 on Discovery) ───────────────── */
static void debug_leds_init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
    for (uint32_t pin = 12; pin <= 15; pin++) {
        GPIOD->MODER &= ~(3U << (pin * 2));
        GPIOD->MODER |=  (1U << (pin * 2));
    }
}

#define LED_GREEN_ON()   (GPIOD->BSRR = (1U << 12))
#define LED_GREEN_OFF()  (GPIOD->BSRR = (1U << (12+16)))
#define LED_ORANGE_ON()  (GPIOD->BSRR = (1U << 13))
#define LED_ORANGE_OFF() (GPIOD->BSRR = (1U << (13+16)))
#define LED_RED_ON()     (GPIOD->BSRR = (1U << 14))
#define LED_RED_OFF()    (GPIOD->BSRR = (1U << (14+16)))
#define LED_BLUE_ON()    (GPIOD->BSRR = (1U << 15))
#define LED_BLUE_OFF()   (GPIOD->BSRR = (1U << (15+16)))

/* ══════════════════════════════════════════════════════════
 *  MAIN
 * ══════════════════════════════════════════════════════════ */

int main(void)
{
    /*
     * HAL_Init() does:
     *  - Sets flash prefetch, instruction/data caches
     *  - Configures SysTick to 1ms interval
     *  - Sets NVIC priority grouping
     */
    HAL_Init();

    /*
     * SystemClock_Config() is generated by CubeMX.
     * After this call:
     *   SYSCLK = 168 MHz, AHB = 168 MHz
     *   APB1 = 42 MHz (timer clock = 84 MHz)
     *   APB2 = 84 MHz (timer clock = 168 MHz)
     */
    SystemClock_Config();

    /* Our register-level init */
    debug_leds_init();
    Motor_Init();

    /* ── 2-second countdown: green LED ─────────────────── */
    LED_GREEN_ON();
    delay_ms(2000);
    LED_GREEN_OFF();

    /* ── Test 1: Forward at 50% for 1s ─────────────────── */
    LED_RED_ON();
    Motor_DriveBoth(50, 50);
    delay_ms(1000);
    Motor_Stop();
    LED_RED_OFF();
    delay_ms(500);

    /* ── Test 2: Backward at 40% for 1s ────────────────── */
    LED_ORANGE_ON();
    Motor_DriveBoth(-40, -40);
    delay_ms(1000);
    Motor_Stop();
    LED_ORANGE_OFF();
    delay_ms(500);

    /* ── Test 3: Turn left 90° ─────────────────────────── */
    LED_BLUE_ON();
    turn_left_90();
    LED_BLUE_OFF();
    delay_ms(500);

    /* ── Test 4: Turn right 90° ────────────────────────── */
    LED_BLUE_ON();
    turn_right_90();
    LED_BLUE_OFF();
    delay_ms(500);

    /* ── Test 5: Left motor only at 70% ────────────────── */
    LED_ORANGE_ON();
    Motor_Drive(MOTOR_LEFT, MOTOR_FORWARD, 70);
    delay_ms(500);
    Motor_Stop();
    LED_ORANGE_OFF();
    delay_ms(200);

    /* ── Test 6: Right motor only at 70% ───────────────── */
    LED_RED_ON();
    Motor_Drive(MOTOR_RIGHT, MOTOR_FORWARD, 70);
    delay_ms(500);
    Motor_Stop();
    LED_RED_OFF();

    /* ── Done: all 4 LEDs on ───────────────────────────── */
    LED_GREEN_ON();
    LED_ORANGE_ON();
    LED_RED_ON();
    LED_BLUE_ON();

    while (1) {
        /* Main loop — maze logic goes here later */
    }
}

/*
 * SystemClock_Config — Generated by CubeMX from the .ioc file.
 *
 * If CubeMX hasn't generated this yet (you imported the .ioc but
 * haven't run code generation), here's the implementation:
 *
 * HSE 8 MHz → PLL → 168 MHz SYSCLK
 * APB1 /4 = 42 MHz (timers 84 MHz)
 * APB2 /2 = 84 MHz (timers 168 MHz)
 */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /* Configure power supply voltage */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /* HSE + PLL configuration */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState       = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM       = 8;
    RCC_OscInitStruct.PLL.PLLN       = 336;
    RCC_OscInitStruct.PLL.PLLP       = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ       = 7;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        while (1);  /* Clock config failed — hang */
    }

    /* Bus prescalers */
    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK
                                     | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1
                                     | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

    /* 5 wait states for 168 MHz at 3.3V */
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK) {
        while (1);  /* Clock config failed — hang */
    }
}

/* HAL expects this for error handling */
void Error_Handler(void)
{
    __disable_irq();
    while (1);
}
